meta:
  title: nextEmu - Multiple Video Game System
  description: Console and Arcade video game emulator for macOS
  url: https://nextemu.com
  author: Craig Erskine

social:
  - title: gitHub
    ico: simple-icons:github
    url: https://github.com/nickybmon/OpenEmu-Silicon/
