meta:
  title: nextEmu - Multiple Video Game System
  description: Console and Arcade video game emulator for macOS
  url: https://nextemu.com
  author: Craig Erskine

social:
  - title: X
    ico: simple-icons:x
    url: https://x.com/nextemu
